## Задача1.1

In [3]:
import numpy as np

In [15]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [16]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [17]:
mean_a = np.mean(a, axis = 0)

In [18]:
mean_a

array([2. , 8.4])

## Задача2.1

In [19]:
a_centered = a - mean_a

In [20]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задача3.1

In [44]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]

In [28]:
a_centered_sp

8.0

In [45]:
a_centered_sp = a_centered_sp / (a.shape[0] - 1)

In [34]:
a_centered_sp

2.0

## Задача4.1*

In [46]:
cov = np.cov(a.T)[0, 1]

In [47]:
a_centered_sp == cov

True

## Задача1.2

In [48]:
import pandas as pd

In [49]:
authors = pd.DataFrame({'author_id':[1, 2, 3,],
                        'author_name':['Тургенев', 'Чехов', 'Островский']})

In [50]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [51]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]})

In [52]:
book

author_id           book_title   price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задача2.2

In [53]:
authors_price = pd.merge(authors, book, on = 'author_id')

In [54]:
authors_price

author_id author_name           book_title   price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задача3.2

In [55]:
top5 = pd.DataFrame(authors_price.nlargest(5, 'price'))

In [56]:
top5

author_id author_name        book_title   price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задача4.2

In [69]:
authors_stat = pd.DataFrame(authors_price.groupby('author_name').agg(min_price=('price','min'),
                                                                     max_price=('price','max'),
                                                                     mean_price=('price','mean')))

In [70]:
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

## Задача5.2*

In [71]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [72]:
authors_price

author_id author_name           book_title   price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [73]:
?pd.pivot_table

In [75]:
book_info = pd.pivot_table(data=authors_price,
                           values='price',
                           index='author_name',
                           columns='cover',
                           aggfunc='sum',
                           fill_value=0,
                           dropna=False)

In [76]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950